spring:
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html


  servlet:
    multipart:
      max-request-size: 5GB
      max-file-size: 5GB


yakir:
  upload:
     dir: D:/data0/uploads/
    #1024*1024=1 048 576,5M=5 242 880
     chunkSize: 5 242 880
